update 8.2
placetopay-org/docker-images pull request #15
Opened 2024-01-29 16:51 UTC by larangogon

2024-01-29 16:58 UTC, larangogon commented
![Captura de pantalla de 2024-01-29 11-57-38](https://github.com/placetopay-org/docker-images/assets/67110144/3a869566-d148-4160-854e-090758fd72c9)

2024-01-29 19:44 UTC, freddiegar requested changes

2024-01-29 19:44 UTC, freddiegar commented on php-vapor/php82-cloudhsm/Dockerfile
> +ENV PHP_EXT_INSTALLER_VERSION=1.5.52
Qué nos impide usar la última versión del instalador? https://github.com/mlocati/docker-php-extension-installer/tags

2024-01-29 19:44 UTC, freddiegar commented on php-vapor/php82-cloudhsm/Dockerfile
> +# (no need to install mbstring, pdo, tokenizer or xml as they are already part of base image)
_Sugerencia_: Otras que necesita ACS son: sodium, openssl. También se instalan en la imágen base, hacer la aclaración en este comentario parece "bueno"

2024-01-29 23:10 UTC, freddiegar approved these changes

2024-01-30 15:26 UTC, merged

2024-01-31 15:24 UTC, freddiegar commented
Merged: https://hub.docker.com/layers/placetopay/php-vapor/php82-cloudhsm/images/sha256-03051575b54ebd00b443c4505a5d70a65a77e841544602494d2823b0c76d721e?context=explore